futaringoto/futarin-api

README.md
api/poetry.lock
api/pyproject.toml
api/routers/raspi.py
api/services/whisper.py
api/utils/config.py

Whisperに対応[#12]

---

README.md
api/routers/raspi.py
api/services/gpt.py

#11 chatGPTが使えるようになった

---

api/routers/raspi.py
api/services/gpt.py
api/services/voicevox.py

#16 /raspi/ の実装完了

---

README.md
api/routers/raspi.py

#18 タグ付け完了 /raspi/

---

api/services/gpt.py

max_tokenを60に設定[#22]

---

api/routers/raspi.py
api/services/tts.py

VOICEVOXからTTSに変更

---

README.md
api/routers/raspi.py
api/services/voicevox_api.py
api/utils/config.py

https://voicevox.su-shiki.com/su-shikiapis/

有志のVOICEVOX APIを用いる

---

README.md

READMEの書き換えで対処[#41]

---

.gitignore
_docker/api/Dockerfile
docker-compose.yml

hot reloadを有効に[#36]

---

docker-compose.yml

nginxを除去した

---

_docker/api/Dockerfile
docker-compose.dev.yml
docker-compose.yml

本番環境でのホットリロードを無効にした

---

.github/workflows/deploy.yml

手動デプロイに変更[#56]

---

api/.flake8
api/poetry.lock
api/pyproject.toml

タイトルの通り
Close #65  (required)
flake8, black, isort を導入した
フォーマッタの実行。diff が大量になるため別ブランチで行う。
- 以下のコマンドで差分確認ができること
```
poetry run flake8
(cd api)
poetry run black . --check
poetry run isort . --check --diff
```

リンタ・フォーマッタを導入した

---

api/main.py
api/routers/raspi.py
api/services/gpt.py
api/services/tts.py
api/services/voicevox.py
api/services/voicevox_api.py
api/services/whisper.py
api/tests/test_main.py
api/utils/config.py
api/utils/log.py

#67 より、実行した。
関連issueなし
isort, blackの実行
-

フォーマッタを実行した

---

_docker/api/Dockerfile
docker-compose.dev.yml
docker-compose.yml

マルチステージビルドの実装

---

api/v1/routers/raspi.py
api/v1/utils/logging.py

print文でのデバッグをlogging に変更
Close #55  (required)
logging の追加
caplog でのテスト
-

loggingの導入

---

CONTRIBUTING.md
Makefile
README.md

`make`コマンドを使って、コマンドをシンプルにした。
Close #83  (required)
開発環境のビルドと実行、リント、フォーマット、テストのラップ
最後三つは、dockerが実行中であることの確認も含まれる
変更に伴う、README, CONTRIBUTING の修正
本番環境のコマンド（使用頻度が少ないのと、混乱を避けるため。
-

Makefileを導入した

---

api/main.py
api/v2/routers/user.py
api/v2/schemas/sandbox.py
api/v2/utils/config.py
api/v2/utils/logging.py

Close #116  (required)
- v2 の追加
- `/users`のCRUD定義
-

v2への分離と/usersの定義

---

api/v2/routers/user.py
api/v2/schemas/user.py

Close #122  (required)
- userのスキーマ定義
- list_users(GET /user)へのダミーデータ挿入
- GET以外の設定
-

userのスキーマ定義

---

api/v2/routers/user.py
api/v2/schemas/user.py

userのリクエストスキーマ定義

---

api/v2/routers/couple.py
api/v2/schemas/couple.py

coupleのレスポンス定義

---

api/v2/routers/couple.py
api/v2/routers/user.py
api/v2/schemas/couple.py
api/v2/schemas/user.py

coupleのリクエスト定義

---

api/v2/schemas/couple.py
api/v2/schemas/user.py

Close #150  (required)
レスポンススキーマに以下を追加
```python
model_config = ConfigDict(from_attributes=True)
```
-

pydantic v2に対応

---

api/main.py
api/v2/routers/raspi.py
api/v2/schemas/raspi.py

変更点はドキュメント参照
Close #126   (required)
- `POST /v2/raspi/{id}` の構築
- `/v1/raspi`と機能変わらず。
- `POST /v2/raspi/{id}/messages`
- こちらはオブジェクトが返るだけです。
-

/v2/raspis の定義

---

.github/workflows/deploy.yml
CONTRIBUTING.md
api/db.py
api/v2/utils/config.py
docker-compose.yml

デプロイ環境でのDB接続実装

---

api/tests/conftest.py
api/tests/cruds/conftest.py
api/tests/test_v2_raspi.py
api/tests/test_v2_user.py
api/v2/routers/pubsub.py

raspi, user のテスト書く

---

api/v2/routers/raspi.py
api/v2/utils/query.py

raspiのuploadを更新

---

api/alembic/env.py
api/v2/routers/raspi.py
api/v2/routers/user.py
api/v2/services/gpt.py

音声ファイルの扱いを変更

---

api/v2/routers/raspi.py
api/v2/services/gpt.py

/v2/raspis/{id}?mode= を追加

---

api/tests/test_v2_user.py
api/v2/cruds/user.py
api/v2/routers/user.py
api/v2/schemas/user.py

userのエラーハンドリング

---

.github/workflows/deploy.yml

deploy.ymlで.env作成

---

api/tests/test_v2_user.py
api/v2/cruds/user.py
api/v2/routers/user.py
api/v2/schemas/user.py

This reverts commit bc410e8d07665f55e5e622f953bd637afd0d92cc.
Close #  (required)
-

Revert "userのエラーハンドリング (#217)"

---

.github/workflows/deploy.yml

This reverts commit 80ca27a4c1cb673e3840f486b8d6a234fe6f54a8.
Close #  (required)
-

Revert "deploy.ymlこうしん (#219)"

---

api/v2/routers/raspi.py
api/v2/services/gpt.py

completionに変更

---

_docker/api/Dockerfile

Dockerfileにrust, cargoを追加
